### ISSUE TITLE
StringSearchEx2   load 敏感词文件空指针

### ISSUE THREAD

**Issue by iwongta** [toolgood/ToolGood.Words#80]
ClassPathResource classPathResource = new ClassPathResource("sensi_words.txt");
StringSearchEx2 s = new StringSearchEx2();
s.Load( classPathResource.getFile().getAbsolutePath());

Exception in thread "main" java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.wochanye.ssc.tool.words.NumHelper.read(NumHelper.java:181)
	at com.wochanye.ssc.tool.words.BaseSearchEx2.Load(BaseSearchEx2.java:93)
	at com.wochanye.ssc.tool.words.BaseSearchEx2.Load(BaseSearchEx2.java:88)
	at com.wochanye.ssc.tool.ToolApplication.main(ToolApplication.java:41)

**Comment by iwongta** [comment]
@toolgood

**Comment by toolgood** [comment]
请看文档，Load 不是用来加载敏感词的，save与load配合使用。。。
